### ISSUE TITLE
Turn off light by default?

### ISSUE THREAD

**Issue by adrienbernede** [GLVis/glvis-js#8]
On the web version, which I think is awesome, I was a bit bothered by the lighting.

On example 1 which has flat surfaces, we can clearly see how lighting can strongly reduce contrast (by that I mean the gradation of colors) and alter the information.

With light: Solution is not rendered properly
<img width="637" alt="Screen Shot 2021-07-14 at 3 19 05 AM" src="https://user-images.githubusercontent.com/51493078/125606041-81e94fc0-9120-4ff1-9395-7b50072c69d3.png">
Without light: OK
<img width="637" alt="Screen Shot 2021-07-14 at 3 18 53 AM" src="https://user-images.githubusercontent.com/51493078/125606050-e14cfc90-3443-4fc5-b4ac-218815d75c5b.png">

To me, light off makes more sense than on, and should be the default. That's only my take on it though.

**Comment by tzanio** [comment]
This is a tricky one -- 3D objects look better with light, but you are absolutely correct that 2D objects (e.g. a cut in a 3D object, or a surface looked from above) should be viewed without light on.

For example in the above plot, if there was no cut and mesh (press `mi`) turning off the light will not look good by default.

The default in GLVis is to have the light on when visualizing 3D meshes, 3D solutions and 2D solutions, and to have the light off when visualizing 2D meshes. This make sense to me, since we have volume/surface objects in the first 3 cases, while in the last case we really want to look at a 2D object.

I think we should keep those defaults, and hopefully users will get used to turning off the light when looking at 2D views. Personally, I have the `Rjl` memorized by my fingers :)

Does this make sense?
Tzanio

**Comment by adrienbernede** [comment]
I didn’t know that there was a change of default for light between 3D and 2D. I agree that "3D objects _look better_ with light", and I guess all depend on the primary goal of GLVis. I was looking at this with a priority on accuracy over rendering of 3D shapes and beauty.

Is there a way to have a "flat light" rather than was looks like a punctual one? It would help a bit, but wouldn't be an outstanding solution I guess.

**Comment by tzanio** [comment]
Maybe I'm not saying it well 😁. It is not a question of beauty. 

A 3D scene without lighting just doesn't look 3D. I believe all major vis tools have lights on by default in 3D.

On the other hand, a proper 2D plot should not have the light on, which I think is the case for all the examples on glvis.org/live. 

It is just one key `l` to switch it on/off... not to mention that we now also have a button for it the GUI 😉

**Comment by adrienbernede** [comment]
OK, OK, it's a one keystroke thing, I can definitely live with that :D.
